version: '1'
services:
  backend:
    build:
      context: backend
    ports:
      - "8080:8080"
  frontend:
    build: 
      context: frontend
    ports:
      - "4200:80"
  db:
    build:
      context: db
    ports:
      - "5432:5432"
